//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Boyner.Invoice
{
    using System.Runtime.Serialization;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InvoiceDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class InvoiceDO : object
    {

        private string BillingAddressField;

        private string BillingCitizenIDField;

        private string BillingCityField;

        private string BillingCountryField;

        private string BillingDistrictField;

        private string BillingNameField;

        private string BillingPhoneField;

        private string BillingTaxNoField;

        private string BillingTaxOfficeField;

        private decimal BonusAmountField;

        private decimal BonusDiscountTotalField;

        private string BonusKeyField;

        private decimal BonusResidualField;

        private decimal BonusRewardTotalField;

        private decimal BonusUnweightedRewardTotalField;

        private string CartTrackingNumberField;

        private System.DateTime CreatedTimeField;

        private string CreatedUserNameField;

        private string CustomerEmailField;

        private string CustomerExternalSystemCodeField;

        private string CustomerFirstNameField;

        private string CustomerFullNameField;

        private int CustomerIDField;

        private string CustomerLastNameField;

        private string CustomerMobilePhoneField;

        private string CustomerMobilePhoneCodeField;

        private decimal DiscountTotalField;

        private string EFatRefField;

        private string ETTNField;

        private string EdspBolNumberField;

        private string FKSellerIDField;

        private string FKSellerStoreIDField;

        private decimal GiftPackTotalField;

        private decimal GiftPackTotalVatField;

        private bool HasAnyGiftCardProductField;

        private bool HasGiftPackField;

        private string HopiAccountIdField;

        private int IDField;

        private System.DateTime InvoiceDateField;

        private string InvoiceNumberField;

        private string InvoicePosNumberField;

        private string InvoiceRefCodeField;

        private string InvoiceStorePrefixField;

        private decimal InvoiceTotalField;

        private Boyner.Invoice.InvoiceType InvoiceTypeField;

        private string InvoiceUserNumberField;

        private bool IsEInvoiceField;

        private bool IsGuestOrderField;

        private bool IsHasGiftPackPaymentField;

        private bool IsHasShipmentPaymentField;

        private bool IsQuickBuyField;

        private System.Collections.Generic.List<Boyner.Invoice.InvoiceItemDO> ItemListField;

        private string OrderCodeField;

        private System.DateTime OrderDateField;

        private string OrderExternalSystemCodeField;

        private int OrderIDField;

        private System.Collections.Generic.List<Boyner.Invoice.OrderMainKeyDO> OrderMainKeyListField;

        private System.Nullable<Boyner.Invoice.OrderType> OrderTypeField;

        private string PackagingLocationCodeField;

        private decimal PayAtDoorFeeField;

        private decimal PayAtDoorTotalField;

        private decimal PayAtDoorTotalVatField;

        private System.Collections.Generic.List<Boyner.Invoice.PaymentDO> PaymentListField;

        private System.Nullable<System.DateTime> SaleInvoiceCreatedTimeField;

        private int SaleInvoiceIDField;

        private string SaleInvoiceNumberField;

        private int SaleInvoiceSequenceNumberField;

        private string SaleOriginField;

        private int SequenceNumberField;

        private decimal ShipmentTotalField;

        private decimal ShipmentTotalVatField;

        private System.Nullable<Boyner.Invoice.ShipmentType> ShipmentTypeField;

        private string StoreCodeField;

        private decimal TotalPaymentMethodFeeField;

        private System.Collections.Generic.List<Boyner.Invoice.VATDO> VATListField;

        private decimal VATTotalField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingAddress
        {
            get
            {
                return this.BillingAddressField;
            }
            set
            {
                this.BillingAddressField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingCitizenID
        {
            get
            {
                return this.BillingCitizenIDField;
            }
            set
            {
                this.BillingCitizenIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingCity
        {
            get
            {
                return this.BillingCityField;
            }
            set
            {
                this.BillingCityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingCountry
        {
            get
            {
                return this.BillingCountryField;
            }
            set
            {
                this.BillingCountryField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingDistrict
        {
            get
            {
                return this.BillingDistrictField;
            }
            set
            {
                this.BillingDistrictField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingName
        {
            get
            {
                return this.BillingNameField;
            }
            set
            {
                this.BillingNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingPhone
        {
            get
            {
                return this.BillingPhoneField;
            }
            set
            {
                this.BillingPhoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingTaxNo
        {
            get
            {
                return this.BillingTaxNoField;
            }
            set
            {
                this.BillingTaxNoField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BillingTaxOffice
        {
            get
            {
                return this.BillingTaxOfficeField;
            }
            set
            {
                this.BillingTaxOfficeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusAmount
        {
            get
            {
                return this.BonusAmountField;
            }
            set
            {
                this.BonusAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusDiscountTotal
        {
            get
            {
                return this.BonusDiscountTotalField;
            }
            set
            {
                this.BonusDiscountTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BonusKey
        {
            get
            {
                return this.BonusKeyField;
            }
            set
            {
                this.BonusKeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusResidual
        {
            get
            {
                return this.BonusResidualField;
            }
            set
            {
                this.BonusResidualField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusRewardTotal
        {
            get
            {
                return this.BonusRewardTotalField;
            }
            set
            {
                this.BonusRewardTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BonusUnweightedRewardTotal
        {
            get
            {
                return this.BonusUnweightedRewardTotalField;
            }
            set
            {
                this.BonusUnweightedRewardTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CartTrackingNumber
        {
            get
            {
                return this.CartTrackingNumberField;
            }
            set
            {
                this.CartTrackingNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedTime
        {
            get
            {
                return this.CreatedTimeField;
            }
            set
            {
                this.CreatedTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreatedUserName
        {
            get
            {
                return this.CreatedUserNameField;
            }
            set
            {
                this.CreatedUserNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerEmail
        {
            get
            {
                return this.CustomerEmailField;
            }
            set
            {
                this.CustomerEmailField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerExternalSystemCode
        {
            get
            {
                return this.CustomerExternalSystemCodeField;
            }
            set
            {
                this.CustomerExternalSystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFirstName
        {
            get
            {
                return this.CustomerFirstNameField;
            }
            set
            {
                this.CustomerFirstNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerFullName
        {
            get
            {
                return this.CustomerFullNameField;
            }
            set
            {
                this.CustomerFullNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerID
        {
            get
            {
                return this.CustomerIDField;
            }
            set
            {
                this.CustomerIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerLastName
        {
            get
            {
                return this.CustomerLastNameField;
            }
            set
            {
                this.CustomerLastNameField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMobilePhone
        {
            get
            {
                return this.CustomerMobilePhoneField;
            }
            set
            {
                this.CustomerMobilePhoneField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerMobilePhoneCode
        {
            get
            {
                return this.CustomerMobilePhoneCodeField;
            }
            set
            {
                this.CustomerMobilePhoneCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DiscountTotal
        {
            get
            {
                return this.DiscountTotalField;
            }
            set
            {
                this.DiscountTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EFatRef
        {
            get
            {
                return this.EFatRefField;
            }
            set
            {
                this.EFatRefField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETTN
        {
            get
            {
                return this.ETTNField;
            }
            set
            {
                this.ETTNField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EdspBolNumber
        {
            get
            {
                return this.EdspBolNumberField;
            }
            set
            {
                this.EdspBolNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FKSellerID
        {
            get
            {
                return this.FKSellerIDField;
            }
            set
            {
                this.FKSellerIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FKSellerStoreID
        {
            get
            {
                return this.FKSellerStoreIDField;
            }
            set
            {
                this.FKSellerStoreIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GiftPackTotal
        {
            get
            {
                return this.GiftPackTotalField;
            }
            set
            {
                this.GiftPackTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal GiftPackTotalVat
        {
            get
            {
                return this.GiftPackTotalVatField;
            }
            set
            {
                this.GiftPackTotalVatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAnyGiftCardProduct
        {
            get
            {
                return this.HasAnyGiftCardProductField;
            }
            set
            {
                this.HasAnyGiftCardProductField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasGiftPack
        {
            get
            {
                return this.HasGiftPackField;
            }
            set
            {
                this.HasGiftPackField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HopiAccountId
        {
            get
            {
                return this.HopiAccountIdField;
            }
            set
            {
                this.HopiAccountIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate
        {
            get
            {
                return this.InvoiceDateField;
            }
            set
            {
                this.InvoiceDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceNumber
        {
            get
            {
                return this.InvoiceNumberField;
            }
            set
            {
                this.InvoiceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoicePosNumber
        {
            get
            {
                return this.InvoicePosNumberField;
            }
            set
            {
                this.InvoicePosNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceRefCode
        {
            get
            {
                return this.InvoiceRefCodeField;
            }
            set
            {
                this.InvoiceRefCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceStorePrefix
        {
            get
            {
                return this.InvoiceStorePrefixField;
            }
            set
            {
                this.InvoiceStorePrefixField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal InvoiceTotal
        {
            get
            {
                return this.InvoiceTotalField;
            }
            set
            {
                this.InvoiceTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public Boyner.Invoice.InvoiceType InvoiceType
        {
            get
            {
                return this.InvoiceTypeField;
            }
            set
            {
                this.InvoiceTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InvoiceUserNumber
        {
            get
            {
                return this.InvoiceUserNumberField;
            }
            set
            {
                this.InvoiceUserNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsEInvoice
        {
            get
            {
                return this.IsEInvoiceField;
            }
            set
            {
                this.IsEInvoiceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGuestOrder
        {
            get
            {
                return this.IsGuestOrderField;
            }
            set
            {
                this.IsGuestOrderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHasGiftPackPayment
        {
            get
            {
                return this.IsHasGiftPackPaymentField;
            }
            set
            {
                this.IsHasGiftPackPaymentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsHasShipmentPayment
        {
            get
            {
                return this.IsHasShipmentPaymentField;
            }
            set
            {
                this.IsHasShipmentPaymentField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsQuickBuy
        {
            get
            {
                return this.IsQuickBuyField;
            }
            set
            {
                this.IsQuickBuyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.InvoiceItemDO> ItemList
        {
            get
            {
                return this.ItemListField;
            }
            set
            {
                this.ItemListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderCode
        {
            get
            {
                return this.OrderCodeField;
            }
            set
            {
                this.OrderCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime OrderDate
        {
            get
            {
                return this.OrderDateField;
            }
            set
            {
                this.OrderDateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OrderExternalSystemCode
        {
            get
            {
                return this.OrderExternalSystemCodeField;
            }
            set
            {
                this.OrderExternalSystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OrderID
        {
            get
            {
                return this.OrderIDField;
            }
            set
            {
                this.OrderIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.OrderMainKeyDO> OrderMainKeyList
        {
            get
            {
                return this.OrderMainKeyListField;
            }
            set
            {
                this.OrderMainKeyListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Boyner.Invoice.OrderType> OrderType
        {
            get
            {
                return this.OrderTypeField;
            }
            set
            {
                this.OrderTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PackagingLocationCode
        {
            get
            {
                return this.PackagingLocationCodeField;
            }
            set
            {
                this.PackagingLocationCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayAtDoorFee
        {
            get
            {
                return this.PayAtDoorFeeField;
            }
            set
            {
                this.PayAtDoorFeeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayAtDoorTotal
        {
            get
            {
                return this.PayAtDoorTotalField;
            }
            set
            {
                this.PayAtDoorTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PayAtDoorTotalVat
        {
            get
            {
                return this.PayAtDoorTotalVatField;
            }
            set
            {
                this.PayAtDoorTotalVatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.PaymentDO> PaymentList
        {
            get
            {
                return this.PaymentListField;
            }
            set
            {
                this.PaymentListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> SaleInvoiceCreatedTime
        {
            get
            {
                return this.SaleInvoiceCreatedTimeField;
            }
            set
            {
                this.SaleInvoiceCreatedTimeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleInvoiceID
        {
            get
            {
                return this.SaleInvoiceIDField;
            }
            set
            {
                this.SaleInvoiceIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaleInvoiceNumber
        {
            get
            {
                return this.SaleInvoiceNumberField;
            }
            set
            {
                this.SaleInvoiceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleInvoiceSequenceNumber
        {
            get
            {
                return this.SaleInvoiceSequenceNumberField;
            }
            set
            {
                this.SaleInvoiceSequenceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SaleOrigin
        {
            get
            {
                return this.SaleOriginField;
            }
            set
            {
                this.SaleOriginField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SequenceNumber
        {
            get
            {
                return this.SequenceNumberField;
            }
            set
            {
                this.SequenceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShipmentTotal
        {
            get
            {
                return this.ShipmentTotalField;
            }
            set
            {
                this.ShipmentTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ShipmentTotalVat
        {
            get
            {
                return this.ShipmentTotalVatField;
            }
            set
            {
                this.ShipmentTotalVatField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<Boyner.Invoice.ShipmentType> ShipmentType
        {
            get
            {
                return this.ShipmentTypeField;
            }
            set
            {
                this.ShipmentTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StoreCode
        {
            get
            {
                return this.StoreCodeField;
            }
            set
            {
                this.StoreCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TotalPaymentMethodFee
        {
            get
            {
                return this.TotalPaymentMethodFeeField;
            }
            set
            {
                this.TotalPaymentMethodFeeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.VATDO> VATList
        {
            get
            {
                return this.VATListField;
            }
            set
            {
                this.VATListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATTotal
        {
            get
            {
                return this.VATTotalField;
            }
            set
            {
                this.VATTotalField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InvoiceType", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public enum InvoiceType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Sale = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Return = -1,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "InvoiceItemDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class InvoiceItemDO : object
    {

        private System.Collections.Generic.List<Boyner.Invoice.BonusDO> BonusListField;

        private System.Collections.Generic.List<Boyner.Invoice.DiscountDO> ButterFlyDiscountListField;

        private string CategoryIDField;

        private decimal DelayChargeAmountField;

        private decimal DelayChargeVatAmountField;

        private System.Collections.Generic.List<Boyner.Invoice.DiscountDO> DiscountListField;

        private string ExternalSystemCodeField;

        private long IDField;

        private bool IsCargoItemField;

        private bool IsFreeOfChargeField;

        private bool IsGiftCardProductField;

        private bool IsProductDiscountForbiddenField;

        private bool IsProductReturnForbiddenField;

        private bool IsReturnedField;

        private short LineNumberField;

        private string ProductCodeField;

        private string ProductDescriptionField;

        private string ReturnReasonField;

        private string ReturnStoreCodeField;

        private decimal SalePriceField;

        private decimal StorePriceField;

        private System.Nullable<decimal> StorePrice1Field;

        private System.Nullable<decimal> StorePrice2Field;

        private System.Nullable<decimal> StorePrice3Field;

        private short StorePriceNumberField;

        private decimal VATAmountField;

        private decimal VATRateField;

        private string VariantBarcodeField;

        private string VariantCdeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.BonusDO> BonusList
        {
            get
            {
                return this.BonusListField;
            }
            set
            {
                this.BonusListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.DiscountDO> ButterFlyDiscountList
        {
            get
            {
                return this.ButterFlyDiscountListField;
            }
            set
            {
                this.ButterFlyDiscountListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CategoryID
        {
            get
            {
                return this.CategoryIDField;
            }
            set
            {
                this.CategoryIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DelayChargeAmount
        {
            get
            {
                return this.DelayChargeAmountField;
            }
            set
            {
                this.DelayChargeAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DelayChargeVatAmount
        {
            get
            {
                return this.DelayChargeVatAmountField;
            }
            set
            {
                this.DelayChargeVatAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<Boyner.Invoice.DiscountDO> DiscountList
        {
            get
            {
                return this.DiscountListField;
            }
            set
            {
                this.DiscountListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalSystemCode
        {
            get
            {
                return this.ExternalSystemCodeField;
            }
            set
            {
                this.ExternalSystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsCargoItem
        {
            get
            {
                return this.IsCargoItemField;
            }
            set
            {
                this.IsCargoItemField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFreeOfCharge
        {
            get
            {
                return this.IsFreeOfChargeField;
            }
            set
            {
                this.IsFreeOfChargeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsGiftCardProduct
        {
            get
            {
                return this.IsGiftCardProductField;
            }
            set
            {
                this.IsGiftCardProductField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProductDiscountForbidden
        {
            get
            {
                return this.IsProductDiscountForbiddenField;
            }
            set
            {
                this.IsProductDiscountForbiddenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsProductReturnForbidden
        {
            get
            {
                return this.IsProductReturnForbiddenField;
            }
            set
            {
                this.IsProductReturnForbiddenField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsReturned
        {
            get
            {
                return this.IsReturnedField;
            }
            set
            {
                this.IsReturnedField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductCode
        {
            get
            {
                return this.ProductCodeField;
            }
            set
            {
                this.ProductCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductDescription
        {
            get
            {
                return this.ProductDescriptionField;
            }
            set
            {
                this.ProductDescriptionField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnReason
        {
            get
            {
                return this.ReturnReasonField;
            }
            set
            {
                this.ReturnReasonField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReturnStoreCode
        {
            get
            {
                return this.ReturnStoreCodeField;
            }
            set
            {
                this.ReturnStoreCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SalePrice
        {
            get
            {
                return this.SalePriceField;
            }
            set
            {
                this.SalePriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal StorePrice
        {
            get
            {
                return this.StorePriceField;
            }
            set
            {
                this.StorePriceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StorePrice1
        {
            get
            {
                return this.StorePrice1Field;
            }
            set
            {
                this.StorePrice1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StorePrice2
        {
            get
            {
                return this.StorePrice2Field;
            }
            set
            {
                this.StorePrice2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> StorePrice3
        {
            get
            {
                return this.StorePrice3Field;
            }
            set
            {
                this.StorePrice3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short StorePriceNumber
        {
            get
            {
                return this.StorePriceNumberField;
            }
            set
            {
                this.StorePriceNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATAmount
        {
            get
            {
                return this.VATAmountField;
            }
            set
            {
                this.VATAmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATRate
        {
            get
            {
                return this.VATRateField;
            }
            set
            {
                this.VATRateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariantBarcode
        {
            get
            {
                return this.VariantBarcodeField;
            }
            set
            {
                this.VariantBarcodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VariantCde
        {
            get
            {
                return this.VariantCdeField;
            }
            set
            {
                this.VariantCdeField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OrderMainKeyDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Che" +
        "ckout")]
    public partial class OrderMainKeyDO : object
    {

        private string KeyField;

        private string ValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key
        {
            get
            {
                return this.KeyField;
            }
            set
            {
                this.KeyField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "OrderType", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Global.Enum")]
    public enum OrderType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        ECommerce = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        WholeSale = 2,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        SalesWithMyAssistant = 3,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Trendyol = 4,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        Hepsiburada = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Morhipo = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pazarama  = 7,
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Amazon = 8,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PaymentDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class PaymentDO : object
    {

        private string AccountNumberField;

        private decimal AmountField;

        private string AuthCodeField;

        private string BankCodeField;

        private string ExternalPaymentTypeCodeField;

        private int IDField;

        private System.Nullable<int> InstallmentCountField;

        private short LineNumberField;

        private string PaymentMethodCodeField;

        private string PaymentNumberField;

        private string PaymentTypeCode1Field;

        private string PaymentTypeCode2Field;

        private string TrxIDField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthCode
        {
            get
            {
                return this.AuthCodeField;
            }
            set
            {
                this.AuthCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BankCode
        {
            get
            {
                return this.BankCodeField;
            }
            set
            {
                this.BankCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExternalPaymentTypeCode
        {
            get
            {
                return this.ExternalPaymentTypeCodeField;
            }
            set
            {
                this.ExternalPaymentTypeCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InstallmentCount
        {
            get
            {
                return this.InstallmentCountField;
            }
            set
            {
                this.InstallmentCountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentMethodCode
        {
            get
            {
                return this.PaymentMethodCodeField;
            }
            set
            {
                this.PaymentMethodCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentNumber
        {
            get
            {
                return this.PaymentNumberField;
            }
            set
            {
                this.PaymentNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentTypeCode1
        {
            get
            {
                return this.PaymentTypeCode1Field;
            }
            set
            {
                this.PaymentTypeCode1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PaymentTypeCode2
        {
            get
            {
                return this.PaymentTypeCode2Field;
            }
            set
            {
                this.PaymentTypeCode2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrxID
        {
            get
            {
                return this.TrxIDField;
            }
            set
            {
                this.TrxIDField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ShipmentType", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Global.Enum")]
    public enum ShipmentType : int
    {

        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 0,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryWithCargo = 1,

        [System.Runtime.Serialization.EnumMemberAttribute()]
        DeliveryWithCC = 2,
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "VATDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class VATDO : object
    {

        private decimal SaleTotalField;

        private decimal SaleTotalWithoutVATField;

        private decimal VATRateField;

        private decimal VATTotalField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaleTotal
        {
            get
            {
                return this.SaleTotalField;
            }
            set
            {
                this.SaleTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal SaleTotalWithoutVAT
        {
            get
            {
                return this.SaleTotalWithoutVATField;
            }
            set
            {
                this.SaleTotalWithoutVATField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATRate
        {
            get
            {
                return this.VATRateField;
            }
            set
            {
                this.VATRateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal VATTotal
        {
            get
            {
                return this.VATTotalField;
            }
            set
            {
                this.VATTotalField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "BonusDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class BonusDO : object
    {

        private decimal AmountField;

        private string CampaignCodeField;

        private string CampaignExternalSystemCodeField;

        private int IDField;

        private short LineNumberField;

        private decimal UnweightedAmountField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignCode
        {
            get
            {
                return this.CampaignCodeField;
            }
            set
            {
                this.CampaignCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignExternalSystemCode
        {
            get
            {
                return this.CampaignExternalSystemCodeField;
            }
            set
            {
                this.CampaignExternalSystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal UnweightedAmount
        {
            get
            {
                return this.UnweightedAmountField;
            }
            set
            {
                this.UnweightedAmountField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "DiscountDO", Namespace = "http://schemas.datacontract.org/2004/07/Entegral.ECommerce.Domain.Integration.Inv" +
        "oice")]
    public partial class DiscountDO : object
    {

        private string CampaignCodeField;

        private string CampaignExternalSystemCodeField;

        private decimal DiscountField;

        private string DocumentNumberField;

        private int IDField;

        private bool IsBonusCampaignField;

        private bool IsDiscountToGrandTotalField;

        private short LineNumberField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignCode
        {
            get
            {
                return this.CampaignCodeField;
            }
            set
            {
                this.CampaignCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CampaignExternalSystemCode
        {
            get
            {
                return this.CampaignExternalSystemCodeField;
            }
            set
            {
                this.CampaignExternalSystemCodeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Discount
        {
            get
            {
                return this.DiscountField;
            }
            set
            {
                this.DiscountField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentNumber
        {
            get
            {
                return this.DocumentNumberField;
            }
            set
            {
                this.DocumentNumberField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID
        {
            get
            {
                return this.IDField;
            }
            set
            {
                this.IDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsBonusCampaign
        {
            get
            {
                return this.IsBonusCampaignField;
            }
            set
            {
                this.IsBonusCampaignField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDiscountToGrandTotal
        {
            get
            {
                return this.IsDiscountToGrandTotalField;
            }
            set
            {
                this.IsDiscountToGrandTotalField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public short LineNumber
        {
            get
            {
                return this.LineNumberField;
            }
            set
            {
                this.LineNumberField = value;
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://boynerortak.com/MASTERDATA/NGI/ORDERS", ConfigurationName = "Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN")]
    public interface SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN
    {

        [System.ServiceModel.OperationContractAttribute(IsOneWay = true, Action = "http://sap.com/xi/WebService/soap1.1")]
        System.Threading.Tasks.Task SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNAsync(Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1 request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "GetNonTransferredInvoiceListResponse", WrapperNamespace = "http://ecommerce.entegral.com.tr/Services/Invoice", IsWrapped = true)]
    public partial class SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://ecommerce.entegral.com.tr/Services/Invoice", Order = 0)]
        public System.Collections.Generic.List<Boyner.Invoice.InvoiceDO> GetNonTransferredInvoiceListResult;

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1()
        {
        }

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1(System.Collections.Generic.List<Boyner.Invoice.InvoiceDO> GetNonTransferredInvoiceListResult)
        {
            this.GetNonTransferredInvoiceListResult = GetNonTransferredInvoiceListResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNChannel : Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient : System.ServiceModel.ClientBase<Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN>, Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient(EndpointConfiguration endpointConfiguration) :
                base(SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient.GetBindingForEndpoint(endpointConfiguration), SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNAsync(Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1 request)
        {
            return base.Channel.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNAsync(request);
        }

        public System.Threading.Tasks.Task SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNAsync(System.Collections.Generic.List<Boyner.Invoice.InvoiceDO> GetNonTransferredInvoiceListResult)
        {
            Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1 inValue = new Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN1();
            inValue.GetNonTransferredInvoiceListResult = GetNonTransferredInvoiceListResult;
            return ((Boyner.Invoice.SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN)(this)).SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYNAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.HTTP_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"http://bbmpodev.boyner.com.tr:50000/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_3RD_MARKETPLACE&receiverParty=&receiverService=&interface=SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN&interfaceNamespace=http%3A%2F%2Fboynerortak.com%2FMASTERDATA%2FNGI%2FORDERS");
            }
            if ((endpointConfiguration == EndpointConfiguration.HTTPS_Port))
            {
                return new System.ServiceModel.EndpointAddress(@"https://bbmpodev.boyner.com.tr:50001/XISOAPAdapter/MessageServlet?senderParty=&senderService=BC_3RD_MARKETPLACE&receiverParty=&receiverService=&interface=SI_BPM_ORDER_GENIUS_CREATE_INVOICE_ABS_ASYN&interfaceNamespace=http%3A%2F%2Fboynerortak.com%2FMASTERDATA%2FNGI%2FORDERS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            HTTP_Port,

            HTTPS_Port,
        }
    }
}
